from sqlalchemy import Column, ForeignKey, Integer, String, Date, Float, Boolean, BigInteger
from sqlalchemy.orm import relationship
from .database import Base


class Student(Base):
    __tablename__ = "student_system"
    id = Column(BigInteger, primary_key=True, index= True)
    studentId = Column(String, index= True)
    fullName = Column(String)
    password = Column(String)
    birthdate = Column(BigInteger)
    birthdateStr = Column(String)
    birthPlace = Column(String)
    departmentId = Column(BigInteger)
    programId = Column(BigInteger)
    majorId = Column(BigInteger)
    majorName = Column(String)
    majorCode = Column(String)
    studentYear = Column(String)
    year = Column(BigInteger)
    gender = Column(BigInteger)
    tokenKey = Column(String)
    phoneNumber = Column(String)
    englishInfo = Column(String)
    creditInfo = Column(String)
    cpa = Column(Float)
    totalCredit = Column(BigInteger)
    graduationDate = Column(BigInteger)
    email = Column(String)
    personalEmail = Column(String)
    idNumber = Column(String)
    idNumberPlace = Column(String)
    idNumberDate = Column(BigInteger)
    lastLoggedIn = Column(BigInteger)
    status = Column(BigInteger)
    rootId = Column(BigInteger)
    uniId = Column(BigInteger)
    classId = Column(BigInteger)
    lastSemester = Column(String)
    classOrder = Column(BigInteger)
    cvUrl = Column(String)
    avatarUrl = Column(String)
    className = Column(String)
    companyName = Column(String)
    scholarShip = Column(String)
    position = Column(String)
    notes = Column(String)
    address = Column(String)
    countryId = Column(BigInteger)
    countryName = Column(String)
    provinceId = Column(BigInteger)
    districtId = Column(BigInteger)
    communeId = Column(BigInteger)
    homeCommune = Column(String)
    homeDistrict = Column(String)
    homeProvince = Column(String)
    homeAddress = Column(String)
    facebookToken = Column(String)
    studyMode = Column(BigInteger)
    studentType = Column(String)
    profileUrl = Column(String)
    facebookId = Column(String)
    relatedEmail = Column(String)
    createdDate = Column(BigInteger)
    lastUpdate = Column(BigInteger)
    tmpState = Column(BigInteger)
    schoolName = Column(String)
    facebookName = Column(String)
    sessionId= Column(String)
    project= Column(String)
    studentClass= Column(String)
    schoolUnit= Column(String)
    major= Column(String)
    program= Column(String)
    available= Column(Boolean)
    profileComplete= Column(Boolean)
    # allEmails = relationship("StudentEmail", back_populates="student")

class StudentEmail(Base):
    __tablename__ = 'student_system_email'
    pri_id = Column(BigInteger, autoincrement=True, primary_key=True)
    id = Column(BigInteger, ForeignKey(Student.id))
    email = Column(String)
    # student = relationship("Student", back_populates="allEmails")
    
    
class RootUnit(Base):
    
    __tablename__ = 'root_unit'
    id = Column(BigInteger, primary_key=True)
    parentId = Column(BigInteger)
    parentName = Column(String)
    type = Column(BigInteger)
    status = Column(BigInteger)
    functionType = Column(BigInteger)
    rootId = Column(BigInteger)
    order = Column(BigInteger)
    api = Column(BigInteger)
    unitId = Column(String)
    logo = Column(String)
    name = Column(String)
    nameEn = Column(String)
    shortNameVi = Column(String)
    shortNameEn = Column(String)
    abbrName = Column(String)
    commonName = Column(String)
    description = Column(String)
    website = Column(String)
    phoneNumber = Column(String)
    faxNumber = Column(String)
    email = Column(String)
    address = Column(String)
    unitCode = Column(String)
    staffNum = Column(BigInteger)
    displayName = Column(String)
    closed = Column(Boolean)
    school = Column(Boolean)
    university = Column(Boolean)
    department = Column(Boolean)
    teachingAndResearch = Column(Boolean)
    teaching = Column(Boolean)




class Teacher(Base):
    __tablename__ = 'teacher'
    id = Column(BigInteger, primary_key=True)
    userName = Column(String)
    password = Column(String)
    fullName = Column(String)
    firstName = Column(String)
    lastName = Column(String)
    gender = Column(BigInteger)
    staffCode = Column(String)
    commonName = Column(String)
    title = Column(BigInteger)
    degree = Column(BigInteger)
    jobType = Column(BigInteger)
    contractType = Column(BigInteger)
    contractNotes = Column(String)
    position = Column(BigInteger)
    departmentId = Column(BigInteger)
    rootId = Column(BigInteger)
    uniId = Column(BigInteger)
    source = Column(BigInteger)
    taxNumber = Column(String)
    notes = Column(String)
    idNumber = Column(String)
    idNumberPlace = Column(String)
    idNumberPlaceId = Column(BigInteger)
    idNumberDate = Column(BigInteger)
    assuranceNumber = Column(String)
    assuranceDate = Column(BigInteger)
    stateOfficialDate = Column(BigInteger)
    prevHiredDate = Column(BigInteger)
    prevPosition = Column(String)
    prevCompany = Column(String)
    hiredDate = Column(BigInteger)
    hiredPosition = Column(String)
    nickName = Column(String)
    qlnnId = Column(BigInteger)
    llctId = Column(BigInteger)
    itLevelId = Column(BigInteger)
    seniorityDate = Column(BigInteger)
    refCode = Column(String)
    bankAccount = Column(String)
    bankInfo = Column(String)
    website = Column(String)
    researchBio = Column(String)
    personalBio = Column(String)
    profileUrl = Column(String)
    candidateGroup = Column(String)
    researchPlan = Column(String)
    researchResume = Column(String)
    birthDate = Column(BigInteger)
    birthPlace = Column(String)
    birthPlaceId = Column(BigInteger)
    birthDateStr = Column(String)
    workEmail = Column(String)
    personalEmail = Column(String)
    workPhoneNumber = Column(String)
    cellPhoneNumber = Column(String)
    workAddress = Column(String)
    homeAddress = Column(String)
    bloodType = Column(String)
    priorityTypeId = Column(BigInteger)
    familyPolicyId = Column(BigInteger)
    highSchoolEduId = Column(BigInteger)
    familyOriginId = Column(BigInteger)
    healthType = Column(BigInteger)
    residentAddress = Column(String)
    residentCountryId = Column(BigInteger)
    residentProvinceId = Column(BigInteger)
    residentDistrictId = Column(BigInteger)
    residentCommuneId = Column(BigInteger)
    homeTownAddress = Column(String)
    homeTownCountryId = Column(BigInteger)
    homeTownProvinceId = Column(BigInteger)
    homeTownDistrictId = Column(BigInteger)
    homeTownCommuneId = Column(BigInteger)
    partyDate = Column(BigInteger)
    officialPartyDate = Column(BigInteger)
    enlistmentDate = Column(BigInteger)
    dischargeDate = Column(BigInteger)
    marriedStatus = Column(BigInteger)
    info = Column(String)
    facebookToken = Column(String)
    facebookId = Column(String)
    facebookName = Column(String)
    relatedEmail = Column(String)
    lastLoggedIn = Column(BigInteger)
    avatarUrl = Column(String)
    projectStatus = Column(BigInteger)
    activated = Column(BigInteger)
    roomId = Column(BigInteger)
    roomName = Column(String)
    probation = Column(BigInteger)
    probationFrom = Column(BigInteger)
    probationTo = Column(BigInteger)
    salaryRaiseDate = Column(BigInteger)
    status = Column(BigInteger)
    tmpStatus = Column(BigInteger)
    tokenKey = Column(String)
    currentRoleId = Column(BigInteger)
    pv = Column(Float)
    pvExternal = Column(Float)
    nc = Column(Float)
    kNc = Column(Float)
    kVt = Column(Float)
    extCoeff = Column(Float)
    nation = Column(String)
    religion = Column(String)
    sessionId = Column(String)
    currentRole = Column(BigInteger)
    rootUnit = Column(BigInteger)
    parentUnit = Column(BigInteger)
    titleItem = Column(String)
    contractTypeItem = Column(String)
    degreeItem = Column(String)
    jobTypeItem = Column(String)
    salary = Column(String)
    admin = Column(Boolean)
    superAdmin = Column(Boolean)
    roleLeve = Column(BigInteger)
    roleSchool = Column(Boolean)
    roleUniversity = Column(Boolean)
    roleDepartment = Column(Boolean)
    eduType = Column(BigInteger)
    vipAdmin = Column(Boolean)
    availableForSalary = Column(Boolean)
    gd = Column(Float)
    adminUnitId = Column(BigInteger)
    candidate = Column(Boolean)
    candidateRejected = Column(Boolean)
    candidatePreparing = Column(Boolean)
    candidateSubmitted = Column(Boolean)
    candidateApproved = Column(Boolean)
    candidateStatusName = Column(String)
    adminQLNguyenVong = Column(Boolean)
    adminStudentClass = Column(Boolean)
    adminClass = Column(Boolean)
    adminPostGrad = Column(Boolean)
    adminUnderGrad = Column(Boolean)
    invited = Column(Boolean)
    externalInvited = Column(Boolean)
    off = Column(Boolean)
    official = Column(Boolean)
    dead = Column(Boolean)
    assistant = Column(Boolean)
    cbkt = Column(Boolean)
    cbhc = Column(Boolean)
    kcd = Column(Float)
    titleFullName = Column(String)
    fullTitle = Column(String)
    languages = Column(String)
    managerUni = Column(Boolean)
    managerSchool = Column(Boolean)


class TeacherEmail(Base):
    __tablename__ = 'teacher_email'
    id = Column(BigInteger, ForeignKey(Teacher.id), primary_key=True)
    email = Column(String, primary_key=True)


class TeacherPhoneNumber(Base):
    __tablename__ = 'teacher_phoneNumber'
    id = Column(BigInteger, ForeignKey(Teacher.id), primary_key=True)
    phoneNumber = Column(String, primary_key=True)
    
class Class(Base):
    __tablename__ = 'class_system'
    id = Column(BigInteger, primary_key=True)
    name = Column(String)
    studentYear = Column(String)
    year = Column(BigInteger)
    rootId = Column(BigInteger, ForeignKey(RootUnit.id))
    teacherId = Column(BigInteger, ForeignKey(Teacher.id))
    monitorId = Column(String)
    secretaryId = Column(String)
    programId = Column(BigInteger)
    status = Column(BigInteger)
    studentNum = Column(BigInteger)
    notes = Column(String)
    # students: List[Student]
    # teacher= Column(BigInteger, ForeignKey(Teacher.id))
    monitor = Column(String)
    secretary = Column(String)





